name: OpenVPN + Pinggy Tunnel (TCP 1194)

on:
  workflow_dispatch:

jobs:
  openvpn:
    runs-on: ubuntu-latest
    steps:
      - name: Cài gói cần thiết
        run: |
          sudo apt update
          sudo apt install -y openvpn openssh-client curl

      - name: Tạo cấu hình server OpenVPN (TCP 1194)
        run: |
          mkdir -p ~/openvpn
          cat <<EOF > ~/openvpn/server.conf
port 1194
proto tcp
dev tun
ifconfig 10.8.0.1 10.8.0.2
keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
verb 3
EOF

      - name: Khởi động OpenVPN server
        run: |
          sudo openvpn --config ~/openvpn/server.conf &
          sleep 5

      - name: Tạo tunnel TCP 1194 qua pinggy.io
        id: tunnel
        run: |
          curl -s -N https://a.pinggy.io --data "forward=tcp://localhost:1194" > tunnel.log &
          sleep 10
          cat tunnel.log | tee /tmp/pinggy_log.txt
          link=$(grep -o 'tcp://.*' /tmp/pinggy_log.txt | head -n1)
          echo "Tunnel link: $link"
          echo "link=$link" >> $GITHUB_OUTPUT

      - name: Tạo file cấu hình client.ovpn
        run: |
          link="${{ steps.tunnel.outputs.link }}"
          host=$(echo "$link" | cut -d/ -f3 | cut -d: -f1)
          port=$(echo "$link" | cut -d: -f3)
          cat <<EOF > client.ovpn
client
dev tun
proto tcp
remote $host $port
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
EOF
          echo "===== FILE client.ovpn ====="
          cat client.ovpn
          echo "============================"

      - name: Giữ workflow chạy 1 tiếng
        run: sleep 3600
