name: OpenVPN + Pinggy Tunnel

on:
  workflow_dispatch:

jobs:
  openvpn:
    runs-on: ubuntu-latest
    steps:
      - name: Cài OpenVPN và curl
        run: |
          sudo apt update
          sudo apt install -y openvpn curl

      - name: Tạo cấu hình server OpenVPN đơn giản
        run: |
          mkdir -p ~/openvpn
          echo "port 1194
proto tcp
dev tun
ifconfig 10.8.0.1 10.8.0.2
keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
verb 3" > ~/openvpn/server.conf

      - name: Khởi động OpenVPN server
        run: |
          sudo openvpn --config ~/openvpn/server.conf &
          sleep 10

      - name: Mở tunnel với Pinggy
        id: tunnel
        run: |
          curl -s -N https://a.pinggy.io --data "forward=tcp://localhost:1194" > tunnel.log &
          sleep 10
          cat tunnel.log | tee /tmp/pinggy_log.txt
          link=$(grep -o 'tcp://.*' /tmp/pinggy_log.txt | head -n1)
          echo "link=$link" >> $GITHUB_OUTPUT
          echo "Tunnel: $link"

      - name: Tạo file client.ovpn từ link Pinggy
        run: |
          link="${{ steps.tunnel.outputs.link }}"
          host=$(echo "$link" | cut -d/ -f3 | cut -d: -f1)
          port=$(echo "$link" | cut -d: -f3)
          echo "client
dev tun
proto tcp
remote $host $port
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3" > client.ovpn
          echo "===== client.ovpn ====="
          cat client.ovpn
          echo "======================="

      - name: Giữ kết nối 1 giờ
        run: sleep 3600
