name: OpenVPN with Pinggy Auto Client

on:
  workflow_dispatch:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Cài OpenVPN + SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn openssh-client easy-rsa net-tools

      - name: Tạo cấu hình OpenVPN server
        run: |
          mkdir -p ~/openvpn
          cd ~/openvpn
          cat <<EOF > server.conf
port 1194
proto tcp
dev tun
ifconfig 10.8.0.1 10.8.0.2
keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
verb 3
EOF

      - name: Khởi động OpenVPN server
        run: |
          sudo openvpn --config ~/openvpn/server.conf &
          sleep 5

      - name: Kết nối tunnel Pinggy (TCP)
        id: pinggy
        run: |
          curl -s -N https://a.pinggy.io --data "forward=tcp://localhost:1194" > link.txt &
          sleep 8
          cat link.txt | tee /tmp/pinggy_link.txt
          # Trích xuất link (ví dụ: tcp://random-a.pinggy.io:12345)
          link=$(grep -o 'tcp://.*' /tmp/pinggy_link.txt | head -n1)
          echo "Tunnel link: $link"
          echo "link=$link" >> $GITHUB_OUTPUT

      - name: Tạo file client.ovpn tự động
        run: |
          link="${{ steps.pinggy.outputs.link }}"
          host=$(echo $link | cut -d/ -f3 | cut -d: -f1)
          port=$(echo $link | cut -d: -f3)
          cat <<EOF > client.ovpn
client
dev tun
proto tcp
remote $host $port
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
EOF
          echo "====== FILE client.ovpn ======"
          cat client.ovpn
          echo "=============================="
          
      - name: Giữ cho workflow không dừng
        run: sleep 3600
